name: SmartDeck
description: Blend AI with Your Workflow.
full_description: 'A more complete description of the mobile app<br>
<br>With a lot of features:
<br>- Multiple AI Models: Support GPT-3.5, GPT-4, LLaMA2, Mistral, etc.
<br>- Prompt Submission Shortcut: Easily send prompts with a keyboard shortcut.
<br>- Quick Text Selection: Capture text for use with a convenient shortcut.
<br>- Save Conversations: Store chats for ongoing or future reference.
<br>- More features on the way...
iOS: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
